import { randomBytes } from 'node:crypto'
import { chmod, mkdir, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { spawn } from 'node:child_process'
import type { ModelRecommendation } from './model-manager.ts'

const proxySource = `import http from 'node:http';import net from 'node:net';import crypto from 'node:crypto';const sessions=new Set();const cookie='yh_session';function sid(req){return (req.headers.cookie||'').split(';').map(x=>x.trim().split('=')).find(x=>x[0]===cookie)?.[1]}async function login(req,res,url){const code=url.searchParams.get('grant');if(!code){res.writeHead(400);return res.end('需要一次性访问授权码');}try{const r=await fetch(process.env.PLATFORM_URL+'/api/hermes/grant/exchange',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});if(!r.ok)throw 0;const id=crypto.randomBytes(32).toString('base64url');sessions.add(id);res.writeHead(303,{'set-cookie':cookie+'='+id+'; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200','location':'/'});res.end()}catch{res.writeHead(401);res.end('授权无效或已过期')}}function headers(req){const h={...req.headers,host:'hermes:9119'};delete h.cookie;return h}const server=http.createServer(async(req,res)=>{const url=new URL(req.url||'/', 'http://local');if(url.pathname==='/login')return login(req,res,url);if(!sessions.has(sid(req))){res.writeHead(303,{location:'/login'});return res.end('请使用平台生成的授权链接');}const upstream=http.request({hostname:'hermes',port:9119,path:req.url,method:req.method,headers:headers(req)},r=>{res.writeHead(r.statusCode||502,r.headers);r.pipe(res)});upstream.on('error',()=>{res.writeHead(502);res.end('Hermes 暂不可用')});req.pipe(upstream)});server.on('upgrade',(req,socket,head)=>{if(!sessions.has(sid(req)))return socket.destroy();const upstream=net.connect(9119,'hermes',()=>{let raw=(req.method||'GET')+' '+(req.url||'/')+' HTTP/1.1\\r\\n';for(const[k,v]of Object.entries(headers(req)))raw+=k+': '+v+'\\r\\n';upstream.write(raw+'\\r\\n');if(head.length)upstream.write(head);socket.pipe(upstream).pipe(socket)});upstream.on('error',()=>socket.destroy())});server.listen(9120,'0.0.0.0');`

export async function installHermesPack(value: { platformUrl: string; modelPath: string; model: ModelRecommendation }) {
  const root = join(homedir(), '.yellow-whale', 'hermes')
  await mkdir(root, { recursive: true, mode: 0o700 })
  const sessionToken = randomBytes(32).toString('base64url')
  const modelConfig = `model:\n  default: "${value.model.id}"\n  provider: "custom"\n  base_url: "http://llama-server:8080/v1"\n  context_length: ${value.model.context}\n  max_tokens: 1024\nproviders:\n  custom:\n    request_timeout_seconds: 180\nauxiliary:\n  compression:\n    context_length: ${value.model.context}\nagent:\n  disabled_toolsets: [terminal, browser]\nterminal:\n  backend: "local"\n  timeout: 30\nplatforms:\n  whatsapp:\n    enabled: false\ncompression:\n  enabled: true\n  threshold: 0.75\n  target_ratio: 0.50\n  protect_last_n: 40\n`
  const compose = `services:\n  llama-server:\n    image: ghcr.io/ggml-org/llama.cpp:server\n    command: [\"-m\", \"/models/${value.model.file}\", \"--alias\", \"${value.model.id}\", \"--host\", \"0.0.0.0\", \"--port\", \"8080\", \"-c\", \"${value.model.context}\"]\n    volumes: [\"${value.modelPath.replaceAll('\\\\','/') }:/models/${value.model.file}:ro\"]\n    ports: [\"127.0.0.1:8080:8080\"]\n    restart: unless-stopped\n  hermes:\n    build:\n      context: https://github.com/NousResearch/hermes-agent.git#v2026.6.5\n    image: yellow-whale-hermes:v2026.6.5\n    environment:\n      OPENAI_BASE_URL: http://llama-server:8080/v1\n      OPENAI_API_KEY: sk-yellow-whale-local\n      HERMES_DASHBOARD: \"1\"\n      HERMES_DASHBOARD_HOST: 0.0.0.0\n      HERMES_DASHBOARD_PORT: \"9119\"\n      HERMES_DASHBOARD_SESSION_TOKEN: ${sessionToken}\n      HERMES_DASHBOARD_INSECURE: \"1\"\n      HERMES_DASHBOARD_NO_OPEN: \"1\"\n      HERMES_DASHBOARD_TUI: \"1\"\n    command: [\"gateway\", \"run\"]\n    expose: [\"9119\"]\n    volumes: [\"./data:/opt/data\", \"./cli-config.yaml:/opt/hermes/cli-config.yaml.example:ro\"]\n    restart: unless-stopped\n    depends_on: [llama-server]\n    security_opt: [\"no-new-privileges:true\"]\n  proxy:\n    image: node:22-alpine\n    command: [\"node\", \"/app/proxy.mjs\"]\n    environment:\n      PLATFORM_URL: ${value.platformUrl}\n    volumes: [\"./proxy.mjs:/app/proxy.mjs:ro\"]\n    ports: [\"127.0.0.1:9120:9120\"]\n    restart: unless-stopped\n    depends_on: [hermes]\n`
  const composePath = join(root, 'compose.yaml'); const proxyPath = join(root, 'proxy.mjs'); const configPath = join(root, 'cli-config.yaml')
  await Promise.all([writeFile(composePath, compose, { mode: 0o600 }), writeFile(proxyPath, proxySource, { mode: 0o600 }), writeFile(configPath, modelConfig, { mode: 0o600 })])
  await Promise.all([chmod(composePath, 0o600), chmod(proxyPath, 0o600), chmod(configPath, 0o600)])
  await new Promise<void>((resolve, reject) => { const child = spawn('docker', ['compose', '-f', composePath, 'up', '-d'], { stdio: 'inherit', cwd: root, windowsHide: true }); child.once('error', reject); child.once('exit', code => code === 0 ? resolve() : reject(new Error('Docker Compose 启动失败'))) })
  return { root, proxyUrl: 'http://127.0.0.1:9120', internalPort: 9119 as const }
}
