'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, ArrowUpRight, Plus, Sparkles, Server, ListTodo, Activity, Wallet, FileText, Languages, FileSearch, Circle, UserRound, Plug, ChevronRight, ShieldCheck, Cpu, Network } from 'lucide-react'
import { Button, buttonVariants } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from '@/components/ui/empty'
import { Progress } from '@/components/ui/progress'
import { useWorkspace } from './workspace-context'
import { cn } from '@/lib/utils'

export function Overview() {
  const { t, setModal, draft, setDraft } = useWorkspace()
  const [mode, setMode] = useState('demand')
  const templates = [
    { icon: Languages, zh: '批量翻译', en: 'Batch translation', textZh: '将每条产品介绍翻译成自然、准确的英文，保留品牌名称和参数。', textEn: 'Translate each product description into natural English, preserving brand names and specifications.' },
    { icon: FileText, zh: '文本摘要', en: 'Text summaries', textZh: '为每条文本生成简明摘要，提炼核心观点。', textEn: 'Summarize each text and extract its key points.' },
    { icon: FileSearch, zh: '信息提取', en: 'Data extraction', textZh: '从每条文本中提取人物、地点和日期，输出 JSON。', textEn: 'Extract people, places, and dates from each text as JSON.' },
  ]
  return <div className="content-enter flex flex-col gap-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight sm:text-[28px]">{t('欢迎来到小黄鲸', 'Welcome to Venus')}</h1><span className="text-primary"><Sparkles className="size-5" strokeWidth={1.6} /></span></div><p className="pt-2 text-sm leading-relaxed text-muted-foreground">{t('连接闲置算力，让想法开始运行。', 'Connect idle power. Put your ideas in motion.')}</p></div><Button variant="outline" onClick={() => setModal('connect')}><Plug data-icon="inline-start" />{t('接入我的算力', 'Connect my compute')}</Button></div>
    <section className="panel overflow-hidden" aria-label={t('创建任务入口', 'Start your task')}>
      <div className="flex items-center justify-between overflow-hidden px-6 pt-6 sm:px-8 sm:pt-7">
        <div className="relative z-10 min-w-0 flex-1 pb-6"><div className="flex items-center gap-2 pb-4 text-sm font-medium text-muted-foreground"><span className="h-px w-5 bg-primary" />{t('小算力，大可能', 'SMALL POWER. BIG POSSIBILITIES.')}</div><h2 className="text-balance text-[27px] font-semibold leading-[1.45] tracking-tight sm:text-[34px]">{t('让每一份算力，', 'Make every bit of')}<br />{t('都有用武之地。', 'computing count.')}</h2><p className="max-w-md pt-3 text-sm leading-6 text-muted-foreground">{t('把任务交给网络，把闲置变成价值。', 'Send your tasks to the network. Give idle power a purpose.')}<br className="hidden sm:block" />{t('你的下一个灵感，从这里出发。', 'Your next idea starts right here.')}</p></div>
        <div className="hidden w-[37%] max-w-80 shrink-0 self-stretch items-center justify-center sm:flex"><Image src="/images/venus-whale.png" alt={t('小黄鲸与本地算力服务器', 'A little yellow whale with local compute servers')} width={600} height={400} priority className="h-48 w-full object-contain xl:h-64 mix-blend-multiply [mask-image:radial-gradient(ellipse_at_center,black_35%,transparent_73%)]" /></div>
      </div>
      <div className="px-5 pb-5 sm:px-8 sm:pb-6"><Tabs value={mode} onValueChange={value => setMode(String(value))}><TabsList variant="line"><TabsTrigger value="demand"><Sparkles data-icon="inline-start" />{t('我有任务', 'I have a task')}</TabsTrigger><TabsTrigger value="supply"><Cpu data-icon="inline-start" />{t('我有算力', 'I have compute')}</TabsTrigger></TabsList></Tabs><div className="pt-4"><form onSubmit={event => { event.preventDefault(); setModal(mode === 'demand' ? 'task' : 'connect') }} className="flex flex-col rounded-xl border bg-background p-2 sm:flex-row sm:items-center"><label htmlFor="quick-task" className="sr-only">{t('描述你的需求', 'Describe what you need')}</label><input id="quick-task" onKeyDown={event => { if (event.key === 'Enter' && (event.nativeEvent.isComposing || event.keyCode === 229)) event.preventDefault() }} value={mode === 'demand' ? draft : ''} readOnly={mode === 'supply'} onChange={event => setDraft(event.target.value)} maxLength={2000} placeholder={mode === 'demand' ? t('例如：帮我把这批产品介绍翻译成英文…', 'For example: translate these product descriptions into English…') : t('通过 AI 助手或 MCP，连接你的 Windows / macOS 设备', 'Connect your Windows or macOS device with an AI assistant')} className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm outline-none placeholder:text-muted-foreground" /><Button variant="strong" type="submit">{mode === 'demand' ? t('创建任务', 'Create task') : t('开始接入', 'Get connected')}<ArrowRight data-icon="inline-end" /></Button></form></div><div className="flex flex-wrap items-center gap-x-4 gap-y-2 pt-3 text-sm text-muted-foreground"><span>{t('试一试', 'Try it')}</span>{templates.map(item => <button key={item.en} className="flex items-center gap-1.5 transition-colors hover:text-foreground" onClick={() => { setMode('demand'); setDraft(t(item.textZh, item.textEn)) }}><item.icon className="size-3.5" />{t(item.zh, item.en)}</button>)}</div></div>
    </section>
    <section aria-label={t('工作区统计', 'Workspace statistics')} className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[
      { icon: ListTodo, zh: '累计任务', en: 'Total tasks', subZh: '你的所有计算任务', subEn: 'All your compute tasks' },
      { icon: Activity, zh: '正在运行', en: 'Running tasks', subZh: '实时查看执行进度', subEn: 'Track work in progress' },
      { icon: Server, zh: '我的在线节点', en: 'My online nodes', subZh: '连接你的闲置算力', subEn: 'Connect your idle power' },
      { icon: Wallet, zh: '累计测试收益', en: 'Test earnings', subZh: '测试资金，不可提现', subEn: 'Test funds · no withdrawals' },
    ].map(item => <Card key={item.en} className="[--card-spacing:--spacing(5)]"><CardHeader><CardTitle><span className="flex items-center justify-between gap-2 text-sm font-normal text-muted-foreground">{t(item.zh, item.en)}<item.icon className="size-[18px]" strokeWidth={1.6} /></span></CardTitle></CardHeader><CardContent><div className="flex items-baseline gap-2"><span className="font-mono text-3xl font-medium">—</span><span className="text-sm text-muted-foreground">{t('待登录', 'Sign in')}</span></div><p className="pt-3 text-sm text-muted-foreground">{t(item.subZh, item.subEn)}</p></CardContent></Card>)}</section>
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
      <section className="panel flex min-w-0 flex-col"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="section-heading">{t('最近任务', 'Recent tasks')}</h2><Link href="/tasks" className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">{t('查看全部', 'View all')}<ArrowUpRight className="size-4" /></Link></div><div className="hidden grid-cols-[1fr_120px_100px] border-b bg-background/50 px-5 py-3 text-sm text-muted-foreground sm:grid"><span>{t('任务名称', 'Task name')}</span><span>{t('状态', 'Status')}</span><span>{t('创建时间', 'Created')}</span></div><Empty className="min-h-56"><EmptyHeader><EmptyMedia variant="icon"><ListTodo /></EmptyMedia><EmptyTitle>{t('下一个好想法，等你开始', 'Your next great idea starts here')}</EmptyTitle><EmptyDescription>{t('创建你的第一个任务，或先了解任务如何运作。', 'Create your first task, or learn how the network works.')}</EmptyDescription></EmptyHeader><Button variant="outline" onClick={() => setModal('task')}><Plus data-icon="inline-start" />{t('创建第一个任务', 'Create your first task')}</Button></Empty><div className="mt-auto flex items-center gap-2 border-t px-5 py-3 text-sm text-muted-foreground"><ShieldCheck className="size-4 shrink-0" />{t('提交前确认数据范围与预算，过程始终由你掌控。', 'Review your data and budget before anything is submitted.')}</div></section>
      <section className="panel"><div className="flex items-center justify-between px-5 pt-5"><h2 className="section-heading">{t('新手起航', 'Your first steps')}</h2><span className="font-mono text-sm text-muted-foreground">0 / 3</span></div><div className="px-5 pb-3 pt-4"><Progress value={0} aria-label={t('入门完成进度', 'Onboarding progress')} /></div><div className="flex flex-col px-2 pb-2">{[
        { icon: UserRound, title: t('建立你的工作空间', 'Set up your workspace'), text: t('创建账户，安全保存任务', 'Create an account to save your work'), modal: 'account' as const },
        { icon: Plug, title: t('连接第一个节点', 'Connect your first node'), text: t('让闲置设备发挥价值', 'Put your idle machine to work'), modal: 'connect' as const },
        { icon: Sparkles, title: t('发起第一个任务', 'Start your first task'), text: t('从一段文本开始探索', 'Start with a simple text task'), modal: 'task' as const },
      ].map(item => <button key={item.title} onClick={() => setModal(item.modal)} className="flex items-center gap-3 rounded-lg px-3 py-4 text-left transition-colors hover:bg-background"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg border text-muted-foreground"><item.icon className="size-4" /></span><span className="flex-1"><span className="block text-sm font-medium">{item.title}</span><span className="block pt-1 text-sm text-muted-foreground">{item.text}</span></span><ChevronRight className="size-4 text-muted-foreground" /></button>)}</div></section>
    </div>
    <section className="flex flex-col items-start justify-between gap-4 rounded-xl border border-primary/25 bg-secondary/45 px-6 py-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-card text-foreground"><Network className="size-6" strokeWidth={1.5} /></div><div><h2 className="text-base font-medium">{t('让你的闲置设备，成为网络的一部分', 'Give your idle machine a place in the network')}</h2><p className="pt-1 text-sm leading-relaxed text-muted-foreground">{t('通过 MCP 或 AI 助手接入，无需开放公网推理端口。', 'Connect through MCP or an AI assistant. No public inference ports.')}</p></div></div><Button variant="outline" onClick={() => setModal('connect')}>{t('了解节点接入', 'Explore node setup')}<ArrowUpRight data-icon="inline-end" /></Button></section>
  </div>
}
